=begin
Swagger atNuda

This is a sample atNuda server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 

OpenAPI spec version: 1.0.0
Contact: xe314m@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "comments".pluralize.to_sym, id: false do |t|
      t.string :uuid
      t.string :content

      t.timestamps
    end

    create_table "corrections".pluralize.to_sym, id: false do |t|
      t.string :uuid
      t.string :content

      t.timestamps
    end

    create_table "portfolios".pluralize.to_sym, id: false do |t|
      t.string :uuid
      t.string :name
      t.string :user_name
      t.string :user_images_url
      t.string :site_url
      t.string :image_urls
      t.string :comments
      t.string :corrections

      t.timestamps
    end

    create_table "portfolios_comments".pluralize.to_sym, id: false do |t|
      t.boolean :myself
      t.string :comment

      t.timestamps
    end

    create_table "portfolios_corrections".pluralize.to_sym, id: false do |t|
      t.boolean :myself
      t.string :correction

      t.timestamps
    end

    create_table "sessions".pluralize.to_sym, id: false do |t|
      t.string :uuid
      t.string :token

      t.timestamps
    end

    create_table "users".pluralize.to_sym, id: false do |t|
      t.string :uuid
      t.string :name
      t.string :category
      t.string :status
      t.string :image_url

      t.timestamps
    end

  end
end
