=begin
Swagger atNuda

This is a sample atNuda server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 

OpenAPI spec version: 1.0.0
Contact: xe314m@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class PortfoliosController < ApplicationController

  def create
    # Your code here
    
    bad_request
    render json: { "date": {"status": 201, "message" => "OK" } } unless error?
  end

  def destroy
    # Your code here

    bad_request
    not_found
    render json: { "date":{ "status": 205, "message" => "OK" } } unless error?
  end

  def show
    # Your code here
    
    data = params.require(:data)
    positions = data[:positions]
    status = data[:status]
    json = { 
      data: [ 
        {
          "portfolio": {
            "uuid": "portxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
            "http://localhost:4200/images/site1.jpeg",
            "http://localhost:4200/images/site2.jpeg",
            "http://localhost:4200/images/site3.jpeg"
            ],
          },
          "explanation": "一言",
          "comments": [
            {
              "myself": true,
              "comment": "私のコメント"
            },
            {
              "myself": false,
              "comment": "誰かのコメント"
            }
          ],
          "corrections": [
            {
              "myself": true,
              "correction": "添削への返信"
            },
            {
              "myself": false,
              "correction": "誰かの添削コメント"
            },
          ],
          "like": 4,
          "user": {
            "uuid": "userxxxxx",
            "name": "john",
            "positions": positions,
            "status": status,
            "user_small_images_url": "https://www.google.com/",
          },
        },
        {
          "portfolio": {
            "uuid": "portxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
            "http://localhost:4200/images/site1.jpeg",
            "http://localhost:4200/images/site2.jpeg",
            "http://localhost:4200/images/site3.jpeg"
            ],
          },
          "explanation": "一言",
          "comments": [
            {
              "myself": true,
              "comment": "私のコメント"
            },
            {
              "myself": false,
              "comment": "誰かのコメント"
            }
          ],
          "corrections": [
            {
              "myself": true,
              "correction": "添削への返信"
            },
            {
              "myself": false,
              "correction": "誰かの添削コメント"
            },
          ],
          "like": 3,
          "user": {
            "uuid": "userxxxxx",
            "name": "john",
            "positions": positions,
            "status": status,
            "user_small_images_url": "https://www.google.com/",
          },
        },
        {
          "portfolio": {
            "uuid": "portxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
            "http://localhost:4200/images/site1.jpeg",
            "http://localhost:4200/images/site2.jpeg",
            "http://localhost:4200/images/site3.jpeg"
            ],
          },
          "explanation": "一言",
          "comments": [
            {
              "myself": true,
              "comment": "私のコメント"
            },
            {
              "myself": false,
              "comment": "誰かのコメント"
            }
          ],
          "corrections": [
            {
              "myself": true,
              "correction": "添削への返信"
            },
            {
              "myself": false,
              "correction": "誰かの添削コメント"
            },
          ],
          "like": 23,
          "user": {
            "uuid": "userxxxxx",
            "name": "john",
            "positions": positions,
            "status": status,
            "user_small_images_url": "https://www.google.com/",
          },
        },
        {
          "portfolio": {
            "uuid": "portxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
            "http://localhost:4200/images/site1.jpeg",
            "http://localhost:4200/images/site2.jpeg",
            "http://localhost:4200/images/site3.jpeg"
            ],
          },
          "explanation": "一言",
          "comments": [
            {
              "myself": true,
              "comment": "私のコメント"
            },
            {
              "myself": false,
              "comment": "誰かのコメント"
            }
          ],
          "corrections": [
            {
              "myself": true,
              "correction": "添削への返信"
            },
            {
              "myself": false,
              "correction": "誰かの添削コメント"
            },
          ],
          "like": 400,
          "user": {
            "uuid": "userxxxxx",
            "name": "john",
            "positions": positions,
            "status": status,
            "user_small_images_url": "https://www.google.com/",
          },
        },
        {
          "portfolio": {
            "uuid": "portxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
            "http://localhost:4200/images/site1.jpeg",
            "http://localhost:4200/images/site2.jpeg",
            "http://localhost:4200/images/site3.jpeg"
            ],
          },
          "explanation": "一言",
          "comments": [
            {
              "myself": true,
              "comment": "私のコメント"
            },
            {
              "myself": false,
              "comment": "誰かのコメント"
            }
          ],
          "corrections": [
            {
              "myself": true,
              "correction": "添削への返信"
            },
            {
              "myself": false,
              "correction": "誰かの添削コメント"
            },
          ],
          "like": 2,
          "user": {
            "uuid": "userxxxxx",
            "name": "john",
            "positions": positions,
            "status": status,
            "user_small_images_url": "https://www.google.com/",
          },
        },
        {
          "portfolio": {
            "uuid": "portxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
            "http://localhost:4200/images/site1.jpeg",
            "http://localhost:4200/images/site2.jpeg",
            "http://localhost:4200/images/site3.jpeg"
            ],
          },
          "explanation": "一言",
          "comments": [
            {
              "myself": true,
              "comment": "私のコメント"
            },
            {
              "myself": false,
              "comment": "誰かのコメント"
            }
          ],
          "corrections": [
            {
              "myself": true,
              "correction": "添削への返信"
            },
            {
              "myself": false,
              "correction": "誰かの添削コメント"
            },
          ],
          "like": 0,
          "user": {
            "uuid": "userxxxxx",
            "name": "john",
            "positions": positions,
            "status": status,
            "user_small_images_url": "https://www.google.com/",
          },
        },
      ]
    }
    bad_request
    not_found
    render json: json unless error?
  end

  def update
    # Your code here
    
    bad_request
    not_found
    render json: { "date": {"status": 200, "message" => "OK" } } unless error?
  end
end
