=begin
Swagger atNuda

This is a sample atNuda server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 

OpenAPI spec version: 1.0.0
Contact: xe314m@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class PortfoliosController < ApplicationController

  def create
    # Your code here
    
    bad_request
    render json: { "date": {"status": 201, "message" => "OK" } } unless error?
  end

  def destroy
    # Your code here

    bad_request
    not_found
    render json: { "date":{ "status": 205, "message" => "OK" } } unless error?
  end

  def show
    # Your code here
    
    data = params.require(:data)
    positions = data[:positions]
    status = data[:status]
    json = { 
      data: [ 
        {
          "uuid": "portxxxxx1",
          "site_url": "https://site-example.com/1",
          "image_urls": [
            "https://example.com/1",
            "https://example.com/2",
            "https://example.com/3"
          ],
          "portfolio_comment": "一言",
          "comments": [
            {
              "myself": true,
              "comment": "私のコメント"
            },
            {
              "myself": false,
              "comment": "誰かのコメント"
            }
          ],
          "corrections": [
            {
              "myself": true,
              "correction": "添削への返信"
            },
            {
              "myself": false,
              "correction": "誰かの添削コメント"
            },
          ],
          "like": 4,
          "follower": 0,
          "user": {
            "name": "john",
            "position": positions,
            "status": status,
            "user_small_images_url": "https://user-small1.com/",
          }
        },
        {
          "uuid": "portxxxxx2",
          "site_url": "https://site-example.com/1",
          "image_urls": [
            "https://example.com/1",
            "https://example.com/2",
            "https://example.com/3"
          ],
          "portfolio_comment": "一言",
          "comments": [
            {
              "myself": true,
              "comment": "私のコメント"
            },
            {
              "myself": false,
              "comment": "誰かのコメント"
            }
          ],
          "corrections": [
            {
              "myself": true,
              "correction": "添削への返信"
            },
            {
              "myself": false,
              "correction": "誰かの添削コメント"
            }
          ],
          "like": 0,
          "follower": 0,
          "user": {
            "name": "john",
            "position": positions,
            "status": status,
            "user_small_images_url": "https://user-small1.com/",
          }
        },
        {
          "uuid": "portxxxxx3",
          "site_url": "https://site-example.com/1",
          "image_urls": [
            "https://example.com/1",
            "https://example.com/2",
            "https://example.com/3"
          ],
          "portfolio_comment": "一言",
          "comments": [
            {
              "myself": true,
              "comment": "私のコメント"
            },
            {
              "myself": false,
              "comment": "誰かのコメント"
            }
          ],
          "corrections": [
            {
              "myself": true,
              "correction": "添削への返信"
            },
            {
              "myself": false,
              "correction": "誰かの添削コメント"
            }
          ],
          "like": 2,
          "follower": 9,
          "user": {
            "name": "john",
            "position": positions,
            "status": status,
            "user_small_images_url": "https://user-small1.com/",
          }
        },
        {
          "uuid": "portxxxxx4",
          "site_url": "https://site-example.com/1",
          "image_urls": [
            "https://example.com/1",
            "https://example.com/2",
            "https://example.com/3"
          ],
          "portfolio_comment": "一言",
          "comments": [
            {
              "myself": true,
              "comment": "私のコメント"
            },
            {
              "myself": false,
              "comment": "誰かのコメント"
            }
          ],
          "corrections": [
            {
              "myself": true,
              "correction": "添削への返信"
            },
            {
              "myself": false,
              "correction": "誰かの添削コメント"
            }
          ],
          "like": 20,
          "follower": 20,
          "user": {
            "name": "john",
            "position": positions,
            "status": status,
            "user_small_images_url": "https://user-small1.com/",
          }
        },
        {
          "uuid": "portxxxxx5",
          "site_url": "https://site-example.com/1",
          "image_urls": [
            "https://example.com/1",
            "https://example.com/2",
            "https://example.com/3"
          ],
          "portfolio_comment": "一言",
          "comments": [
            {
              "myself": true,
              "comment": "私のコメント"
            },
            {
              "myself": false,
              "comment": "誰かのコメント"
            }
          ],
          "corrections": [
            {
              "myself": true,
              "correction": "添削への返信"
            },
            {
              "myself": false,
              "correction": "誰かの添削コメント"
            }
          ],
          "like": 100,
          "follower": 200,
          "user": {
            "name": "john",
            "position": positions,
            "status": status,
            "user_small_images_url": "https://user-small1.com/",
          }
        }
      ]
    }
    bad_request
    not_found
    render json: json unless error?
  end

  def update
    # Your code here
    
    bad_request
    not_found
    render json: { "date": {"status": 200, "message" => "OK" } } unless error?
  end
end
