=begin
Swagger atNuda

This is a sample atNuda server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 

OpenAPI spec version: 1.0.0
Contact: xe314m@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class SessionsController < ApplicationController

  def create
    # Your code here

    render json: { date: {status: 200, "token" => "xxxxx", message="OK"} } 
  end

  def destroy
    # Your code here

    render json: { date: {status: 200, "message" => "OK"} } 
  end
end
