=begin
Swagger atNuda

This is a sample atNuda server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 

OpenAPI spec version: 1.0.0
Contact: xe314m@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class UsersController < ApplicationController
  USER_ERROR400_JSON = {"error": { "status": 400, "message": "Invalid uuid supplied" } }
  USER_ERROR404_JSON = {"error": { "status": 404, "message": "Invalid User not found" } }
  PAGE_ERROR400_JSON = {"error": { "status": 400, "message": "Invalid page supplied" } }
  PAGE_ERROR404_JSON = {"error": { "status": 404, "message": "Invalid page not found" } }

  def destroy
    # Your code here

    bad_request
    not_found
    render json: { date: {status: 200, "message" => "OK" } } unless error?
  end

  def get_user_by_uuid

    json = {
      data: {
        "user": {
          "uuid": "userxxxxxxx1",
          "name": "john",
          "positions": ["フロントエンド", "デザイナー"],
          "status": "転職中",
          "user_large_image_url": "http://localhost:4200/images/large_user1.jpeg",
          "user_small_images_url": "http://localhost:4200/images/small_user1.jpeg",
        },
        "portforios": [
          {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
               "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              }
            ],
            "like": 4,
            "user": {
              "uuid": "userxxxxx",
              "name": "john",
              "positions": ["フロントエンド", "バックエンド"],
              "status": status,
              "user_small_images_url": "https://www.google.com/",
            }
          },
          {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
               "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              }
            ],
            "like": 2,
            "user": {
              "uuid": "userxxxxx",
              "name": "john",
              "positions": ["フロントエンド", "バックエンド"],
              "status": status,
              "user_small_images_url": "https://www.google.com/",
            }
          },
          {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
               "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              }
            ],
            "like": 0,
            "user": {
              "uuid": "userxxxxx",
              "name": "john",
              "positions": ["フロントエンド", "バックエンド"],
              "status": status,
              "user_small_images_url": "https://www.google.com/",
            }
          },
          {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
               "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              }
            ],
            "like": 9,
            "user": {
              "uuid": "userxxxxx",
              "name": "john",
              "positions": ["フロントエンド", "バックエンド"],
              "status": status,
              "user_small_images_url": "https://www.google.com/",
            }
          },
          {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
               "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              }
            ],
            "like": 1,
            "user": {
              "uuid": "userxxxxx",
              "name": "john",
              "positions": ["フロントエンド", "バックエンド"],
              "status": status,
              "user_small_images_url": "https://www.google.com/",
            }
          },
          {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
               "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              }
            ],
            "like": 4,
            "user": {
              "uuid": "userxxxxx",
              "name": "john",
              "positions": ["フロントエンド", "バックエンド"],
              "status": status,
              "user_small_images_url": "https://www.google.com/",
            }
          },
          {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
               "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              }
            ],
            "like": 6,
            "user": {
              "uuid": "userxxxxx",
              "name": "john",
              "positions": ["フロントエンド", "バックエンド"],
              "status": status,
              "user_small_images_url": "https://www.google.com/",
            }
          },
          {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
               "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              }
            ],
            "like": 80,
            "user": {
              "uuid": "userxxxxx",
              "name": "john",
              "positions": ["フロントエンド", "バックエンド"],
              "status": status,
              "user_small_images_url": "https://www.google.com/",
            }
          },
          {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
               "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              }
            ],
            "like": 100,
            "user": {
              "uuid": "userxxxxx",
              "name": "john",
              "positions": ["フロントエンド", "バックエンド"],
              "status": status,
              "user_small_images_url": "https://www.google.com/",
            }
          },
        ]
      }
    }

    bad_request
    not_found
    render json: json unless error?
  end

  def get_likes_portfolios_of_user_by_uuid
    json = {
      data: [
        {
          "user": {
            "uuid": "userxxxxxxx2",
            "name": "john",
            "positions": ["ワールドエンド", "バックエンド"],
            "status": "転職中",
            "user_small_images_url": "http://localhost:4200/images/small_user1.jpeg",
          },
          "portforio": {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
                "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              },
            ],
            "like": 4,
          },
        },
        {
          "user": {
            "uuid": "userxxxxxxx3",
            "name": "john",
            "positions": ["ワールドエンド", "バックエンド"],
            "status": "転職中",
            "user_small_images_url": "http://localhost:4200/images/small_user1.jpeg",
          },
          "portforio": {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
                "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              },
            ],
            "like": 8,
          },
        },
        {
          "user": {
            "uuid": "userxxxxxxx4",
            "name": "john",
            "positions": ["ワールドエンド", "バックエンド"],
            "status": "転職中",
            "user_small_images_url": "http://localhost:4200/images/small_user1.jpeg",
          },
          "portforio": {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
                "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              },
            ],
            "like": 1,
          },
        },
        {
          "user": {
            "uuid": "userxxxxxxx5",
            "name": "john",
            "positions": ["ワールドエンド", "バックエンド"],
            "status": "転職中",
            "user_small_images_url": "http://localhost:4200/images/small_user1.jpeg",
          },
          "portforio": {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
                "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              },
            ],
            "like": 9,
          },
        },
        {
          "user": {
            "uuid": "userxxxxxxx6",
            "name": "john",
            "positions": ["ワールドエンド", "バックエンド"],
            "status": "転職中",
            "user_small_images_url": "http://localhost:4200/images/small_user1.jpeg",
          },
          "portforio": {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
                "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              },
            ],
            "like": 40,
          },
        },
        {
          "user": {
            "uuid": "userxxxxxxx7",
            "name": "john",
            "positions": ["ワールドエンド", "バックエンド"],
            "status": "転職中",
            "user_small_images_url": "http://localhost:4200/images/small_user1.jpeg",
          },
          "portforio": {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
                "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              },
            ],
            "like": 100,
          },
        },
        {
          "user": {
            "uuid": "userxxxxxxx8",
            "name": "john",
            "positions": ["ワールドエンド", "バックエンド"],
            "status": "転職中",
            "user_small_images_url": "http://localhost:4200/images/small_user1.jpeg",
          },
          "portforio": {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
                "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              },
            ],
            "like": 200,
          },
        },
        {
          "user": {
            "uuid": "userxxxxxxx9",
            "name": "john",
            "positions": ["ワールドエンド", "バックエンド"],
            "status": "転職中",
            "user_small_images_url": "http://localhost:4200/images/small_user1.jpeg",
          },
          "portforio": {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
                "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              },
            ],
            "like": 0,
          },
        },
        {
          "user": {
            "uuid": "userxxxxxxx10",
            "name": "john",
            "positions": ["ワールドエンド", "バックエンド"],
            "status": "転職中",
            "user_small_images_url": "http://localhost:4200/images/small_user1.jpeg",
          },
          "portforio": {
            "uuid": "portxxxxxxx1",
            "site_url": "https://www.google.com/",
            "image_urls": [
              "http://localhost:4200/images/site1.jpeg",
              "http://localhost:4200/images/site2.jpeg",
              "http://localhost:4200/images/site3.jpeg"
            ],
            "explanation": "一言",
            "comments": [
              {
                "myself": true,
                "comment": "私のコメント"
              },
              {
                "myself": false,
                "comment": "誰かのコメント"
              }
            ],
            "corrections": [
              {
                "myself": true,
                "correction": "添削への返信"
              },
              {
                "myself": false,
                "correction": "誰かの添削コメント"
              },
            ],
            "like": 0,
          },
        },
      ]
    }

    bad_request
    not_found
    render json: json unless error?
  end

  def update
    # Your code here
    
    bad_request
    not_found
    render json: { "date": {"status": 200, "message" => "OK" } } unless error?
  end
end
